import React from 'react'
import { Banknote, Check, CheckCircle2, Clock3, CreditCard, Download, LoaderCircle, QrCode, ReceiptText } from 'lucide-react'

const money=value=>`BDT ${Number(value||0).toLocaleString()}`
function downloadReceipt({order,payment,restaurantName,tableNumber,items,total}){
  const escape=value=>String(value??'').replace(/[^\x20-\x7E]/g,'?').replaceAll('\\','\\\\').replaceAll('(','\\(').replaceAll(')','\\)')
  const lines=[restaurantName,'PAYMENT RECEIPT',`Order #${order.orderNumber||String(order.id||'').replace('#','')}`,`Table ${tableNumber}`,`Paid: ${new Date().toLocaleString()}`,'',...items.map(item=>`${item.quantity} x ${item.name}  ${money(Number(item.price)*Number(item.quantity))}`),'',`TOTAL  ${money(total)}`,`Method: ${String(payment.method||'').replaceAll('_',' ').toUpperCase()}`,`Reference: ${payment.customer_reference||payment.reference||'-'}`,'','Payment verified. Thank you!']
  const stream=`BT\n/F1 11 Tf\n50 790 Td\n${lines.map((line,index)=>`${index?'0 -22 Td\n':''}(${escape(line)}) Tj`).join('\n')}\nET`,objects=[null,'<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>']
  let pdf='%PDF-1.4\n',offsets=[0];for(let index=1;index<objects.length;index+=1){offsets[index]=pdf.length;pdf+=`${index} 0 obj\n${objects[index]}\nendobj\n`}const xref=pdf.length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n${offsets.slice(1).map(offset=>`${String(offset).padStart(10,'0')} 00000 n `).join('\n')}\ntrailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`
  const url=URL.createObjectURL(new Blob([pdf],{type:'application/pdf'})),link=document.createElement('a');link.href=url;link.download=`BiteLink-receipt-${order.orderNumber||order.id}.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
}
export default function BillAndPayment({order,payment,onPay,tableNumber='12',restaurantName='Restaurant',submitting=false,error=''}) {
  const items=Array.isArray(order?.itemDetails)?order.itemDetails:[],subtotal=order?.subtotal!=null?Number(order.subtotal):items.reduce((sum,item)=>sum+Number(item.price||0)*Number(item.quantity||0),0),discount=Number(order?.discount||0),total=order?.total!=null?Number(order.total):Math.max(0,subtotal-discount)
  const [method,setMethod]=React.useState('bangla_qr'),[reference,setReference]=React.useState(''),[validation,setValidation]=React.useState(''),status=String(payment?.status||'').toLowerCase(),verified=status==='verified',waiting=['pending','submitted'].includes(status)
  const submit=()=>{if(reference.trim().length<2){setValidation(method==='bangla_qr'?'Enter the transaction ID from your payment app.':'Enter a payment reference, such as bKash, card, or cash.');return}setValidation('');onPay({method,reference:reference.trim()})}
  if(!order)return <section className="customer-panel bill-panel bill-empty"><ReceiptText size={28}/><h2>No bill yet</h2><p>Your bill will appear here after your order has been served.</p></section>
  if(verified)return <section className="customer-panel bill-panel payment-complete" role="status" aria-live="assertive"><div className="success-bloom"><span><Check size={34}/></span><i/><i/><i/></div><span className="section-kicker">PAYMENT VERIFIED</span><h2>Thank you!</h2><p>Your payment has been confirmed. We hope you enjoyed your meal.</p><div className="verified-summary"><span>Order <b>#{order.orderNumber||String(order.id).replace('#','')}</b></span><span>Total paid <b>{money(total)}</b></span></div><button className="receipt-download" onClick={()=>downloadReceipt({order,payment,restaurantName,tableNumber,items,total})}><Download size={16}/> Download bill PDF</button></section>
  return <section className="customer-panel bill-panel"><div className="customer-panel-heading"><div><span className="section-kicker">TABLE {tableNumber} · ORDER #{order.orderNumber||String(order.id).replace('#','')}</span><h2>Your bill</h2></div><span className={`status ${waiting?'amber':''}`}>{waiting?'VERIFYING':'READY'}</span></div><div className="bill-items" role="table" aria-label="Bill items">{items.map(item=><div className="bill-item" role="row" key={item.id||item.name}><span><strong>{item.name}</strong><small>{item.quantity} × {money(item.price)}</small></span><b>{money(Number(item.quantity)*Number(item.price))}</b></div>)}</div><div className="bill-totals"><span>Subtotal <b>{money(subtotal)}</b></span>{discount>0&&<span>Discount <b>−{money(discount)}</b></span>}<strong>Grand total <b>{money(total)}</b></strong></div>{waiting?<div className="verification-wait"><span><LoaderCircle size={25}/></span><h3>Your bill is being verified</h3><p>The restaurant team has received your payment details. This screen will update automatically shortly.</p><small><Clock3 size={13}/> Usually takes only a moment</small></div>:<><div className="payment-choice"><button className={method==='bangla_qr'?'active':''} onClick={()=>setMethod('bangla_qr')}><QrCode size={17}/> Bangla QR</button><button className={method==='card'?'active':''} onClick={()=>setMethod('card')}><CreditCard size={17}/> Card / other</button><button className={method==='cash'?'active':''} onClick={()=>setMethod('cash')}><Banknote size={17}/> Cash</button></div>{method==='bangla_qr'&&<div className="bangla-qr"><div className="bangla-qr-mark"><QrCode size={70}/><b>বাংলা QR</b></div><p>Scan with any supported banking or mobile financial service app.</p></div>}<label className="payment-reference">{method==='bangla_qr'?'Transaction ID':'Payment reference'}<input value={reference} onChange={event=>setReference(event.target.value)} placeholder={method==='bangla_qr'?'e.g. 9F7K2M8P':'e.g. bKash, Visa card, cash'} autoComplete="off"/><small>{method==='bangla_qr'?'Required to match your Bangla QR payment.':'Tell the team how you paid or add a useful reference.'}</small></label>{(validation||error)&&<p className="payment-error">{validation||error}</p>}<button className="detail-add-button payment-submit" disabled={submitting} onClick={submit}>{submitting?<LoaderCircle className="spin" size={16}/>:<CheckCircle2 size={16}/>} {submitting?'Submitting…':"I've paid"}</button></>}</section>
}
