import { useState } from 'react'
import { Banknote, Check, CheckCircle2, Clock3, CreditCard, Download, LoaderCircle, QrCode, ReceiptText } from 'lucide-react'

const money=value=>`BDT ${Number(value||0).toLocaleString('en-BD')}`
const dhakaDate=value=>new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'medium',timeZone:'Asia/Dhaka'}).format(new Date(value||Date.now()))
const shortId=value=>String(value||'').toUpperCase().slice(0,8)
const ascii=value=>String(value??'').replace(/[^\x20-\x7E]/g,'?')

async function logoData(url){
  if(!url)return null
  try{const image=new Image();image.crossOrigin='anonymous';await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url});const canvas=document.createElement('canvas');canvas.width=180;canvas.height=180;const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,180,180);const ratio=Math.min(150/image.naturalWidth,150/image.naturalHeight);const width=image.naturalWidth*ratio,height=image.naturalHeight*ratio;context.drawImage(image,(180-width)/2,(180-height)/2,width,height);return canvas.toDataURL('image/png')}catch{return null}
}

async function downloadReceipt({order,payment,restaurantName,restaurantAddress,logoUrl,tableNumber,items,total}){
  const {jsPDF}=await import('jspdf'),doc=new jsPDF({unit:'mm',format:'a4'}),pageWidth=210,margin=18,accent=[233,118,86],ink=[26,47,39],muted=[105,119,111]
  doc.setFillColor(...ink);doc.rect(0,0,pageWidth,58,'F');doc.setFillColor(...accent);doc.rect(0,55,pageWidth,3,'F')
  const logo=await logoData(logoUrl);if(logo){doc.setFillColor(255,255,255);doc.roundedRect(margin,12,30,30,4,4,'F');doc.addImage(logo,'PNG',margin+2,14,26,26)}
  const titleX=logo?54:margin;doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(19);doc.text(ascii(restaurantName||'Restaurant'),titleX,21);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(215,226,220);doc.text(doc.splitTextToSize(ascii(restaurantAddress||'Restaurant receipt'),pageWidth-titleX-margin),titleX,28)
  doc.setFillColor(83,151,101);doc.roundedRect(151,16,41,12,6,6,'F');doc.setFont('helvetica','bold');doc.setFontSize(9);doc.setTextColor(255,255,255);doc.text('PAYMENT VERIFIED',171.5,23.5,{align:'center'})
  let y=72;doc.setTextColor(...ink);doc.setFontSize(22);doc.text('Payment receipt',margin,y);doc.setDrawColor(220,226,221);doc.line(margin,y+7,pageWidth-margin,y+7)
  y+=18;const receiptId=`BL-${shortId(payment.id)}-${order.orderNumber||shortId(order.id)}`;doc.setFontSize(8);doc.setTextColor(...muted);doc.text('RECEIPT ID',margin,y);doc.text('ORDER NUMBER',78,y);doc.text('TABLE',145,y);doc.setFontSize(11);doc.setFont('helvetica','bold');doc.setTextColor(...ink);doc.text(receiptId,margin,y+6);doc.text(`#${order.orderNumber||shortId(order.id)}`,78,y+6);doc.text(String(tableNumber),145,y+6)
  y+=20;doc.setFillColor(247,249,246);doc.roundedRect(margin,y,pageWidth-margin*2,20,3,3,'F');doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(...muted);doc.text('VERIFIED AT (BANGLADESH STANDARD TIME)',margin+6,y+7);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(...ink);doc.text(dhakaDate(payment.verified_at),margin+6,y+14)
  y+=32;doc.setFontSize(9);doc.setTextColor(...muted);doc.text('ITEM',margin,y);doc.text('QTY',126,y,{align:'right'});doc.text('AMOUNT',pageWidth-margin,y,{align:'right'});doc.setDrawColor(210,219,212);doc.line(margin,y+3,pageWidth-margin,y+3);y+=11
  items.forEach(item=>{doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(...ink);doc.text(ascii(item.name),margin,y);doc.setFont('helvetica','normal');doc.setTextColor(...muted);doc.text(`${item.quantity} x ${money(item.price)}`,126,y,{align:'right'});doc.setFont('helvetica','bold');doc.setTextColor(...ink);doc.text(money(Number(item.quantity)*Number(item.price)),pageWidth-margin,y,{align:'right'});y+=9})
  doc.setDrawColor(210,219,212);doc.line(margin,y,pageWidth-margin,y);y+=10;doc.setFontSize(10);doc.setTextColor(...muted);doc.text('Grand total',margin,y);doc.setFont('helvetica','bold');doc.setFontSize(17);doc.setTextColor(...accent);doc.text(money(total),pageWidth-margin,y,{align:'right'})
  y+=17;doc.setFillColor(252,245,241);doc.roundedRect(margin,y,pageWidth-margin*2,46,4,4,'F');doc.setFontSize(8);doc.setTextColor(...muted);doc.setFont('helvetica','normal');doc.text('PAYMENT METHOD',margin+7,y+9);doc.text('TRANSACTION REFERENCE',margin+7,y+23);doc.text('CONFIRMED BY',110,y+9);doc.text('UNIQUE ORDER ID',110,y+23);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(...ink);doc.text(ascii(String(payment.method||'').replaceAll('_',' ').toUpperCase()),margin+7,y+15);doc.text(ascii(payment.customer_reference||payment.reference||'-'),margin+7,y+29);doc.text(ascii(payment.verified_by_name||'Authorized restaurant staff'),110,y+15);doc.setFontSize(7.5);doc.text(ascii(order.id),110,y+29,{maxWidth:78})
  y+=60;doc.setTextColor(83,151,101);doc.setFontSize(12);doc.setFont('helvetica','bold');doc.text('Thank you for dining with us!',pageWidth/2,y,{align:'center'});doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(...muted);doc.text('This digitally generated receipt confirms that the restaurant has verified your payment.',pageWidth/2,y+7,{align:'center'});doc.text('BiteLink secure table payment',pageWidth/2,282,{align:'center'})
  doc.save(`BiteLink-verified-receipt-${order.orderNumber||shortId(order.id)}.pdf`)
}

export default function BillAndPayment({order,payment,onPay,tableNumber='12',restaurantName='Restaurant',restaurantAddress='',logoUrl='',submitting=false,error=''}){
  const items=Array.isArray(order?.itemDetails)?order.itemDetails:[],subtotal=order?.subtotal!=null?Number(order.subtotal):items.reduce((sum,item)=>sum+Number(item.price||0)*Number(item.quantity||0),0),discount=Number(order?.discount||0),total=order?.total!=null?Number(order.total):Math.max(0,subtotal-discount)
  const [method,setMethod]=useState('bangla_qr'),[reference,setReference]=useState(''),[validation,setValidation]=useState(''),[pdfBusy,setPdfBusy]=useState(false),status=String(payment?.status||'').toLowerCase(),verified=status==='verified',waiting=['pending','submitted'].includes(status)
  const submit=()=>{if(reference.trim().length<2){setValidation(method==='bangla_qr'?'Enter the transaction ID from your payment app.':'Enter a payment reference, such as bKash, card, or cash.');return}setValidation('');onPay({method,reference:reference.trim()})}
  const savePdf=async()=>{setPdfBusy(true);try{await downloadReceipt({order,payment,restaurantName,restaurantAddress,logoUrl,tableNumber,items,total})}finally{setPdfBusy(false)}}
  if(!order)return <section className="customer-panel bill-panel bill-empty"><ReceiptText size={28}/><h2>No bill yet</h2><p>Your bill will appear here after your order has been served.</p></section>
  if(verified)return <section className="customer-panel bill-panel payment-complete" role="status" aria-live="assertive"><div className="success-bloom"><span><Check size={34}/></span><i/><i/><i/></div>{logoUrl&&<img className="receipt-restaurant-logo" src={logoUrl} alt=""/>}<span className="section-kicker">PAYMENT VERIFIED · {shortId(payment.id)}</span><h2>{restaurantName}</h2><p>Thank you! Your payment has been confirmed by <b>{payment.verified_by_name||'authorized restaurant staff'}</b>.</p><div className="verified-summary"><span>Order <b>#{order.orderNumber||shortId(order.id)}</b></span><span>Total paid <b>{money(total)}</b></span></div><small className="receipt-verified-time"><Clock3 size={13}/> {dhakaDate(payment.verified_at)} BST</small><button className="receipt-download" disabled={pdfBusy} onClick={savePdf}>{pdfBusy?<LoaderCircle className="spin" size={16}/>:<Download size={16}/>} {pdfBusy?'Generating receipt…':'Download verified PDF bill'}</button></section>
  return <section className="customer-panel bill-panel"><div className="customer-panel-heading"><div><span className="section-kicker">TABLE {tableNumber} · ORDER #{order.orderNumber||shortId(order.id)}</span><h2>Your bill</h2></div><span className={`status ${waiting?'amber':'coral'}`}>{waiting?'VERIFYING':'PAYMENT DUE'}</span></div><div className="bill-items" role="table" aria-label="Bill items">{items.map(item=><div className="bill-item" role="row" key={item.id||item.name}><span><strong>{item.name}</strong><small>{item.quantity} × {money(item.price)}</small></span><b>{money(Number(item.quantity)*Number(item.price))}</b></div>)}</div><div className="bill-totals"><span>Subtotal <b>{money(subtotal)}</b></span>{discount>0&&<span>Discount <b>−{money(discount)}</b></span>}<strong>Grand total <b>{money(total)}</b></strong></div>{waiting?<div className="verification-wait"><span><LoaderCircle size={25}/></span><h3>Your bill is being verified</h3><p>The restaurant team has received your payment details. This screen will update automatically shortly.</p><small><Clock3 size={13}/> Usually takes only a moment</small></div>:<><div className="payment-choice"><button className={method==='bangla_qr'?'active':''} onClick={()=>setMethod('bangla_qr')}><QrCode size={17}/> Bangla QR</button><button className={method==='card'?'active':''} onClick={()=>setMethod('card')}><CreditCard size={17}/> Card / other</button><button className={method==='cash'?'active':''} onClick={()=>setMethod('cash')}><Banknote size={17}/> Cash</button></div>{method==='bangla_qr'&&<div className="bangla-qr"><div className="bangla-qr-mark"><QrCode size={70}/><b>বাংলা QR</b></div><p>Scan with any supported banking or mobile financial service app.</p></div>}<label className="payment-reference">{method==='bangla_qr'?'Transaction ID':'Payment reference'}<input value={reference} onChange={event=>setReference(event.target.value)} placeholder={method==='bangla_qr'?'e.g. 9F7K2M8P':'e.g. bKash, Visa card, cash'} autoComplete="off"/><small>{method==='bangla_qr'?'Required to match your Bangla QR payment.':'Tell the team how you paid or add a useful reference.'}</small></label>{(validation||error)&&<p className="payment-error">{validation||error}</p>}<button className="detail-add-button payment-submit" disabled={submitting} onClick={submit}>{submitting?<LoaderCircle className="spin" size={16}/>:<CheckCircle2 size={16}/>} {submitting?'Submitting…':"I've paid"}</button></>}</section>
}
