import { ArrowRight, CalendarDays, Clock3, Mail, MapPin, Phone, Play, Utensils } from 'lucide-react'
import FoodCard from './FoodCard'
import CategoryTabs from './CategoryTabs'
import OfferSection from './OfferSection'

const images = {
  hero: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=90',
  about: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=90',
  bar: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=900&q=90',
}
const eventImages = [
  'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=600&q=90',
  'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=600&q=90',
  'https://images.unsplash.com/photo-1519671282429-b44660ead0a7?auto=format&fit=crop&w=600&q=90',
]

export default function BistroLanding({ restaurantName, outlet, content, onMenu, menuItems, currentPage, pageCount, onPageChange, onSelect, onAdd, categories, category, onCategoryChange }) {
  return <div className="bistro-site"><OfferSection onMenu={onMenu} variant="midnight" content={content} />
    <div className="bistro-utility"><span>502-333-0719</span><span><Mail size={10} /> Orders@mgsprimetime.com</span><span><MapPin size={10} /> 7017 Global Drive, Louisville</span></div>
    <nav className="bistro-nav"><div className="bistro-brand"><strong>{restaurantName}</strong><small>PRIME TIME<br />BAR AND EVENT CENTER</small></div><div className="bistro-links"><a className="active" href="#bistro-home">Home</a><a href="#bistro-about">About us</a><a href="#bistro-menus">Menus</a><a href="#bistro-bar">Bar</a><a href="#bistro-events">Event</a><a href="#bistro-contact">Contact</a></div><button onClick={onMenu} aria-label="Open menu"><Utensils size={15} /></button></nav>
    <section className="bistro-reference-hero" id="bistro-home"><div><span className="bistro-kicker">Fresh food · fresh moments</span><h1>{restaurantName}<br /><em>BAR AND EVENT CENTER</em></h1><p>Good food, good drinks, and even better memories.</p><button onClick={onMenu}>Online order <ArrowRight size={14} /></button></div><div className="bistro-reference-hero-image"><img src={images.hero} alt="Fresh food prepared in a restaurant" /><span>● <b>●</b> ●</span></div></section>
    <section className="bistro-reference-about" id="bistro-about"><div><img src={images.about} alt="Dining at the restaurant" /></div><div><span className="bistro-kicker">About us</span><h2><em>About</em> us</h2><p>{restaurantName} is a place where great food and good company come together.</p><p>{outlet}, Dhaka · Open daily for dinner and drinks.</p><button onClick={onMenu}>Learn more <ArrowRight size={14} /></button></div></section>
    <section className="bistro-reference-menus" id="bistro-menus"><div className="bistro-section-title"><span className="bistro-kicker">Our kitchen</span><h2><em>Restaurant</em> menus</h2></div><CategoryTabs categories={categories} activeCategory={category} onChange={onCategoryChange} /><div className="bistro-live-menu-grid">{menuItems.map((item) => <FoodCard item={item} key={item.id || item.name} onSelect={onSelect} onAdd={onAdd} />)}</div>{pageCount > 1 && <nav className="bistro-live-pagination" aria-label="Menu pages"><button onClick={() => onPageChange(currentPage - 1)} disabled={currentPage === 1} aria-label="Previous menu page">‹</button>{Array.from({ length: pageCount }, (_, index) => index + 1).map((page) => <button className={currentPage === page ? 'active' : ''} onClick={() => onPageChange(page)} aria-current={currentPage === page ? 'page' : undefined} key={page}>{page}</button>)}<button onClick={() => onPageChange(currentPage + 1)} disabled={currentPage === pageCount} aria-label="Next menu page">›</button></nav>}</section>
    <section className="bistro-reference-bar" id="bistro-bar"><div><span className="bistro-kicker">Cocktails · music · company</span><h2><em>Our</em> bar</h2><p>A lively room for a late drink, a quick bite, or an evening that turns into something more.</p><button onClick={onMenu}>Learn more <ArrowRight size={14} /></button></div><div className="bistro-bar-image"><img src={images.bar} alt="Restaurant bar" /><button aria-label="Play bar video"><Play size={18} fill="currentColor" /></button></div></section>
    <section className="bistro-reference-events" id="bistro-events"><div className="bistro-section-title"><span className="bistro-kicker">What is happening</span><h2><em>Latest</em> events</h2></div><div className="bistro-event-grid">{eventImages.map((image, index) => <article key={image}><img src={image} alt="Restaurant event" /><span><CalendarDays size={11} /> Oct {22 + index * 5}</span><small><MapPin size={10} /> Louisville, Kentucky</small><h3>LOREM IPSUM DOLOR</h3><p>Good food, good people, and a night worth remembering.</p><button onClick={onMenu}>View details <ArrowRight size={12} /></button></article>)}</div></section>
    <footer className="bistro-reference-footer" id="bistro-contact"><div className="bistro-footer-brand"><div className="bistro-brand"><strong>{restaurantName}</strong><small>PRIME TIME<br />BAR AND EVENT CENTER</small></div><p>Good food. Good drinks. Good times.</p></div><div><h3>Quick links</h3><a href="#bistro-home">Home</a><a href="#bistro-about">About us</a><a href="#bistro-menus">Restaurant menus</a><a href="#bistro-events">Event</a></div><div><h3>Contact</h3><p><MapPin size={11} /> 7017 Global Drive<br />Louisville, KY 40258</p><p><Phone size={11} /> 502-333-0719</p><p><Mail size={11} /> Orders@mgsprimetime.com</p></div><div><h3>Working hours</h3><p><Clock3 size={11} /> Monday - Thursday<br />11am - 11pm</p><p><Clock3 size={11} /> Friday & Saturday<br />11am - 2am</p></div><small className="bistro-copyright">© 2022 MG's Prime Time · All Rights Reserved</small></footer>
  </div>
}
