import { useState } from 'react'
import { ArrowLeft, ArrowRight, CheckCircle2, Minus, Plus, ShoppingBag, X } from 'lucide-react'
const promotion=item=>{const tiers=(item.offers||[]).flatMap(offer=>offer.tiers||[]).filter(tier=>item.quantity>=Number(tier.quantity)),percent=tiers.length?Math.max(...tiers.map(tier=>Number(tier.percent))):0;return {percent,amount:item.price*item.quantity*percent/100}}
const comboPromotion=items=>{const byId=new Map(items.map(item=>[item.id,item])),offers=[...new Map(items.flatMap(item=>item.offers||[]).filter(offer=>offer.offerType==='combo').map(offer=>[offer.id,offer])).values()];return offers.reduce((sum,offer)=>{const selected=(offer.menuItemIds||[]).map(id=>byId.get(id));if(selected.some(item=>!item))return sum;const uses=Math.min(...selected.map(item=>item.quantity)),regular=selected.reduce((total,item)=>total+Number(item.price),0);return sum+Math.max(0,regular-Number(offer.comboPrice||regular))*uses},0)}
export default function CartDrawer({cart,onChange,onClose,onAddMore,onPlaceOrder,tableNumber='12',submitting=false,error=''}){
 const [confirming,setConfirming]=useState(false),items=Object.values(cart),subtotal=items.reduce((sum,item)=>sum+item.price*item.quantity,0),tierDiscount=items.reduce((sum,item)=>sum+promotion(item).amount,0),comboDiscount=comboPromotion(items),discount=Math.max(tierDiscount,comboDiscount),total=subtotal-discount
 return <div className="cart-backdrop" onClick={onClose}><aside className="cart-drawer" onClick={event=>event.stopPropagation()}><div className="drawer-heading"><div><span className="section-kicker">{confirming?'Final confirmation':`Table ${tableNumber}`}</span><h2>{confirming?'Confirm order':'Review your cart'}</h2></div><button className="close-button" onClick={onClose}><X size={20}/></button></div>
 {!items.length?<div className="empty-cart"><ShoppingBag size={28}/><p>Your cart is empty.<br/>Add a dish to get started.</p><button className="cart-add-more" onClick={onAddMore}><Plus size={15}/> Browse menu</button></div>:confirming?<div className="cart-confirm"><CheckCircle2 size={35}/><h3>Ready to send this order?</h3><p>Discounts are verified again when the restaurant receives your order.</p><div>{items.map(item=>{const deal=promotion(item);return <span key={item.id}><b>{item.quantity} × {item.name}{deal.percent>0&&<small>{deal.percent}% offer applied</small>}</b><strong>BDT {(item.price*item.quantity-deal.amount).toLocaleString()}</strong></span>})}</div><section><span>Total</span><b>BDT {total.toLocaleString()}</b></section>{error&&<p className="auth-error">{error}</p>}<footer><button onClick={()=>setConfirming(false)}><ArrowLeft size={15}/> Back to cart</button><button className="place-order" disabled={submitting} onClick={()=>onPlaceOrder({subtotal,discount,total})}>{submitting?'Placing order…':'Confirm & place order'}<ArrowRight size={17}/></button></footer></div>:<><div className="cart-list">{items.map(item=>{const deal=promotion(item);return <div className="cart-row" key={item.id}>{item.image?<img className="cart-item-image" src={item.image} alt=""/>:<span className="cart-item-image cart-item-placeholder"><ShoppingBag size={17}/></span>}<div className="cart-item-copy"><b>{item.name}</b><span>BDT {item.price} × {item.quantity}</span><strong>BDT {(item.price*item.quantity).toLocaleString()}</strong>{item.offers?.[0]&&<small className={deal.percent?'cart-offer applied':'cart-offer'}>{deal.percent?`${deal.percent}% off applied · Save BDT ${deal.amount.toLocaleString()}`:item.offers[0].tiers.map(tier=>`Buy ${tier.quantity}, save ${tier.percent}%`).join(' · ')}</small>}</div><div className="quantity-control"><button onClick={()=>onChange(item.id,-1)}><Minus size={14}/></button><b>{item.quantity}</b><button onClick={()=>onChange(item.id,1)}><Plus size={14}/></button></div></div>})}</div><button className="cart-add-more" onClick={onAddMore}><Plus size={15}/> Add more food</button><div className="cart-summary"><div><span>Subtotal</span><b>BDT {subtotal.toLocaleString()}</b></div>{discount>0&&<div className="offer-discount-total"><span>Offer discount</span><b>-BDT {discount.toLocaleString()}</b></div>}<div className="total"><span>Total</span><b>BDT {total.toLocaleString()}</b></div><button className="place-order" onClick={()=>setConfirming(true)}>Review & confirm <ArrowRight size={17}/></button></div></>}</aside></div>
}
