import { ArrowRight, Check, ChefHat, Clock3, MapPin, Search, Star } from 'lucide-react'
import CategoryTabs from './CategoryTabs'
import FoodCard from './FoodCard'
import OfferSection from './OfferSection'
import MenuPagination from './MenuPagination'

export default function ExpressLanding({ restaurantName, outlet, content, onMenu, menuItems, currentPage, pageCount, onPageChange, onSelect, onAdd, categories, category, onCategoryChange }) {
  const heroItem = menuItems[0]
  return <div className="express-site"><OfferSection onMenu={onMenu} variant="express" content={content} />
    <nav className="express-nav"><a href="#express-home" className="express-logo"><span><ChefHat size={16} /></span>{restaurantName}</a><div><a className="active" href="#express-home">Home</a><a href="#express-menu">Foods</a><a href="#express-process">Services</a><a href="#express-reviews">Reviews</a></div><button onClick={onMenu}>Order now</button></nav>
    <section className="express-hero" id="express-home"><div className="express-hero-copy"><span className="express-eyebrow">Fresh from our kitchen</span><h1>Delivery of fresh<br />and <em>hot food</em><br />within 40 minutes</h1><p>Every dish is prepared to order with bold flavour, quality ingredients, and care.</p><div className="express-actions"><button onClick={onMenu}>Order now <ArrowRight size={14} /></button><a href="#express-menu">See menu</a></div><div className="express-facts"><span><Clock3 size={14} /><b>25–40 min</b> Delivery</span><span><MapPin size={14} /><b>{outlet}</b> Dhaka</span><span><Star size={14} /><b>4.9 rating</b> Guests love us</span></div></div><div className="express-plate"><i /><img src={heroItem?.image} alt={heroItem?.name || 'Fresh restaurant dish'} /><span className="express-orbit one" /><span className="express-orbit two" /></div></section>
    <section className="express-menu" id="express-menu"><div className="express-section-head"><div><span className="express-eyebrow">Restaurant menu</span><h2>Choose your dishes</h2></div><label><Search size={13} /><input aria-label="Search dishes" placeholder="Search for food" /></label></div><CategoryTabs categories={categories} activeCategory={category} onChange={onCategoryChange} /><div className="express-food-grid">{menuItems.map((item) => <FoodCard item={item} key={item.id || item.name} onSelect={onSelect} onAdd={onAdd} />)}</div><MenuPagination currentPage={currentPage} pageCount={pageCount} onPageChange={onPageChange} /></section>
    <section className="express-lunch"><span>Business Lunch</span><h2>Freshly cooked. Right on time.</h2><button onClick={onMenu}>Order lunch <ArrowRight size={13} /></button></section>
    <section className="express-process" id="express-process"><div className="express-process-art"><div><ChefHat size={76} /><span /></div></div><div><span className="express-eyebrow">Fast delivery within an hour</span><h2>Fresh food.<br /><em>Simple process.</em></h2>{[['Choose your meal', 'Pick a favourite from the live restaurant menu.'], ['We cook it fresh', 'Our kitchen prepares every order immediately.'], ['Enjoy at your table', 'Track progress and pay when you are ready.']].map(([title, copy], index) => <article key={title}><b>0{index + 1}</b><span><strong>{title}</strong><small>{copy}</small></span><Check size={14} /></article>)}</div></section>
    <section className="express-reviews" id="express-reviews"><span className="express-eyebrow">What guests say</span><h2>Reviews</h2><div>{['The food arrived hot, fresh, and beautifully packed.', 'Ordering was effortless and every dish tasted fantastic.', 'Fast service, generous portions, and wonderful flavours.'].map((review, index) => <article key={review}><span>{'★★★★★'}</span><p>{review}</p><b>{['Nadia Rahman', 'Jubair Hasan', 'Samia Khan'][index]}</b><small>Verified guest</small></article>)}</div></section>
    <footer className="express-footer"><a href="#express-home" className="express-logo"><span><ChefHat size={16} /></span>{restaurantName}</a><p>{outlet}, Dhaka · Fresh food, delivered fast.</p><button onClick={onMenu}>Order now <ArrowRight size={13} /></button></footer>
  </div>
}
