import { useEffect, useState } from 'react'
import { ArrowRight, Check, Clock3, Package, Sparkles } from 'lucide-react'

const steps=['PENDING','CONFIRMED','PREPARING','READY','SERVING','SERVED']
const labels=['Received','Confirmed','Preparing','Ready','Serving','Served']
const remainingLabel=value=>{if(!value)return 'Waiting for kitchen estimate';const seconds=Math.max(0,Math.ceil((new Date(value).getTime()-Date.now())/1000));if(seconds<=0)return 'Ready any moment';const minutes=Math.floor(seconds/60),rest=seconds%60;return `${minutes}:${String(rest).padStart(2,'0')} remaining`}

export default function OrderTracker({order,onOrderMore}){
  const [,tick]=useState(0)
  useEffect(()=>{if(!order?.estimatedReadyAt||['READY','SERVING','SERVED'].includes(order.status))return undefined;const timer=window.setInterval(()=>tick(value=>value+1),1000);return()=>window.clearInterval(timer)},[order?.estimatedReadyAt,order?.status])
  if(!order)return <section className="customer-panel empty-order"><Package size={22}/><h2>Your table is ready</h2><p>Place an order and the kitchen will keep you posted here.</p></section>
  const currentIndex=Math.max(0,steps.indexOf(order.status)),hasItemDetails=order.itemDetails?.length>0,status=order.status.charAt(0)+order.status.slice(1).toLowerCase(),activeEstimate=!['READY','SERVING','SERVED'].includes(order.status)
  return <section className="customer-panel tracker-panel"><div className="customer-panel-heading"><div><span className="section-kicker">Table {order.tableId||'12'} · live order</span><h2>Order {order.id}</h2></div><span className="status green">{status}</span></div><p className="tracker-message"><Sparkles size={15}/>{order.status==='SERVED'?<>Your order has been served. Enjoy your meal!</>:order.status==='SERVING'?<>Your order is on the way to your table.</>:order.status==='READY'?<>Your order is ready to serve.</>:<>Kitchen estimate: <b className="eta-countdown">{activeEstimate?remainingLabel(order.estimatedReadyAt):'Ready'}</b></>}</p><div className="order-timeline order-timeline-six">{steps.map((step,index)=><div className={index<=currentIndex?'complete':''} key={step}><span>{index<currentIndex?<Check size={13}/>:index===currentIndex?<Clock3 size={13}/>:index+1}</span><small>{labels[index]}</small></div>)}</div><div className="tracker-details"><span className="section-kicker">Order details</span>{hasItemDetails?<div className="tracker-items">{order.itemDetails.map(item=><div className="tracker-item" key={item.id||item.name}><span><b>{item.name}</b><small>BDT {item.price} × {item.quantity}</small></span><strong>BDT {(item.price*item.quantity).toLocaleString()}</strong></div>)}</div>:<p className="tracker-item-summary">{order.items}</p>}<div className="tracker-totals">{order.subtotal!=null&&<span>Subtotal <b>BDT {order.subtotal.toLocaleString()}</b></span>}{order.discount>0&&<span>Discount <b>- BDT {order.discount.toLocaleString()}</b></span>}<strong>Total <b>{order.total!=null?`BDT ${order.total.toLocaleString()}`:order.amount}</b></strong></div></div><button className="text-button" onClick={onOrderMore}>Order more <ArrowRight size={13}/></button></section>
}
