import { ArrowRight, ChefHat, Clock3, Gift, Heart, Leaf, Search, ShoppingBag, Sparkles, Star } from 'lucide-react'
import CategoryTabs from './CategoryTabs'
import FoodCard from './FoodCard'
import OfferSection from './OfferSection'

export default function SageLanding({ restaurantName, outlet, onMenu, menuItems, onSelect, onAdd, categories, category, onCategoryChange }) {
  const hero = menuItems[0]
  return <div className="sage-site"><OfferSection onMenu={onMenu} variant="sage" />
    <nav className="sage-nav"><a href="#sage-home"><Leaf size={18} />Foodb</a><div><a className="active" href="#sage-home">Home</a><a href="#sage-menu">Menu</a><a href="#sage-special">About us</a><a href="#sage-reviews">Reviews</a></div><button onClick={onMenu}>Order food</button></nav>
    <section className="sage-hero" id="sage-home"><div className="sage-hero-copy"><small>Exploring the delicious world</small><h1>The Perfect Space<br />to Enjoy best<br />Food</h1><p>Fresh ingredients, thoughtful recipes, and a warm table made for memorable meals.</p><label><Search size={14} /><input placeholder="Search your favourite dish" aria-label="Search menu" /></label><div><button onClick={onMenu}>Book a table</button><button onClick={onMenu}>View menu <ArrowRight size={13} /></button></div><article><img src={menuItems[4]?.image || hero?.image} alt="Chef recommendation" /><span><b>Chef's choice</b><small>{outlet}, Dhaka</small></span><strong>BDT {menuItems[4]?.price || 590}</strong></article></div><div className="sage-hero-plate"><i /><img src={hero?.image} alt={hero?.name || 'Signature dish'} /><span className="one"><Star size={12} /> 4.9</span><span className="two"><Clock3 size={12} /> 25 min</span></div></section>
    <section className="sage-benefits">{[[Gift, 'Discount voucher', 'Save more on every visit'], [Leaf, 'Fresh healthy food', 'Local produce, cooked daily'], [Clock3, 'Fast serve on table', 'Quick service, no compromise']].map(([Icon, title, copy]) => <article key={title}><span><Icon size={18} /></span><div><b>{title}</b><small>{copy}</small></div></article>)}</section>
    <section className="sage-special" id="sage-special"><div className="sage-special-dishes">{menuItems.slice(1, 3).map((item) => <article key={item.id}><button onClick={() => onSelect(item)}><img src={item.image} alt={item.name} /></button><div><b>{item.name}</b><span><Star size={10} fill="currentColor" /> 4.9</span></div><strong>BDT {item.price}</strong><button onClick={() => onAdd(item)} aria-label={`Add ${item.name}`}><ShoppingBag size={13} /></button></article>)}</div><div><span>Made with care</span><h2>Our Special Dishes</h2><p>Professionally prepared seasonal favourites with balanced spices, vibrant produce, and flavours worth sharing.</p><button onClick={onMenu}>Discover more <ArrowRight size={13} /></button></div></section>
    <section className="sage-menu" id="sage-menu"><header><span>Fresh from our kitchen</span><h2>Explore Our Menu</h2></header><CategoryTabs categories={categories} activeCategory={category} onChange={onCategoryChange} /><div className="sage-food-grid">{menuItems.slice(0, 6).map((item) => <FoodCard item={item} key={item.id || item.name} onSelect={onSelect} onAdd={onAdd} />)}</div></section>
    <section className="sage-trending"><header><span>Worth discovering</span><h2>Trending Recipes</h2></header><div>{menuItems.slice(6, 11).map((item) => <button key={item.id} onClick={() => onSelect(item)}><img src={item.image} alt={item.name} /><span>{item.name}</span></button>)}</div></section>
    <section className="sage-chef"><div><ChefHat size={72} /><i /></div><article><span>Meet our master chef</span><h2>Crafted by experience</h2><p>Our kitchen team brings thoughtful technique and joyful hospitality to every plate.</p><b>Chef Zihad Islam</b><small>Executive chef</small></article></section>
    <section className="sage-reviews" id="sage-reviews"><div className="sage-review-art"><Heart size={65} /><Sparkles size={24} /></div><article><span>Our customer's says</span><h2>Food that makes people smile</h2><p>“Fresh, beautifully served, and full of flavour. The whole ordering experience was wonderfully easy.”</p><b>Ms Zihad Islam</b><small>★★★★★ · Verified customer</small></article></section>
    <footer className="sage-footer"><a href="#sage-home"><Leaf size={17} />Foodb</a><p>{restaurantName} · {outlet}, Dhaka</p><button onClick={onMenu}>Order now <ArrowRight size={13} /></button></footer>
  </div>
}
