import { ArrowRight, ChefHat, Clock3, Flame, MapPin, Quote } from 'lucide-react'
import CategoryTabs from './CategoryTabs'
import FoodCard from './FoodCard'
import OfferSection from './OfferSection'

export default function WorldPlateLanding({ restaurantName, outlet, onMenu, menuItems, onSelect, onAdd, categories, category, onCategoryChange }) {
  const hero = menuItems[1] || menuItems[0]
  const featured = menuItems[3] || menuItems[0]
  return <div className="worldplate-site"><OfferSection onMenu={onMenu} variant="worldplate" />
    <nav className="worldplate-nav"><a className="worldplate-logo" href="#worldplate-home"><Flame size={17} />WorldPlate</a><div><a className="active" href="#worldplate-home">Home</a><a href="#worldplate-menu">Menu</a><a href="#worldplate-best">Best dishes</a><a href="#worldplate-chef">Chef</a></div><button onClick={onMenu}>Book a table</button></nav>
    <section className="worldplate-hero" id="worldplate-home"><div><span className="worldplate-kicker">Flavours without borders</span><h1>Experience the<br /><em>Taste</em> of the<br />World</h1><p>Discover handcrafted dishes inspired by kitchens across the globe, served fresh at your table.</p><button onClick={onMenu}>Explore menu <ArrowRight size={14} /></button><div className="worldplate-meta"><span><Clock3 size={14} /><b>Open daily</b> 11 AM–11 PM</span><span><MapPin size={14} /><b>{outlet}</b> Dhaka</span></div></div><div className="worldplate-hero-dish"><i /><img src={hero?.image} alt={hero?.name || 'Signature world cuisine'} /><span><Flame size={13} /> Chef's choice</span></div></section>
    <aside className="worldplate-offer"><div><small>Great food and lots<br />of discounted prices</small><strong>50%<sup>off</sup></strong><button onClick={onMenu}>Claim offer</button></div><img src={menuItems[2]?.image || hero?.image} alt="Discounted restaurant dish" /></aside>
    <section className="worldplate-menu" id="worldplate-menu"><header><span className="worldplate-kicker">Explore the menu</span><h2>Popular around the world</h2></header><CategoryTabs categories={categories} activeCategory={category} onChange={onCategoryChange} /><div className="worldplate-food-grid">{menuItems.slice(0, 6).map((item) => <FoodCard item={item} key={item.id || item.name} onSelect={onSelect} onAdd={onAdd} />)}</div></section>
    <section className="worldplate-best" id="worldplate-best"><div className="worldplate-best-art"><span>Our Best <em>Delivered</em></span><img src={featured?.image} alt={featured?.name || 'Featured dish'} /><i className="worldplate-ring" /></div><div><span className="worldplate-kicker">This week's favourite</span><h2>{featured?.name || 'Breakfast Specials'}</h2><p>A generous plate layered with fresh ingredients, vivid spices, and the warmth of our kitchen.</p><strong>BDT {featured?.price || 590}</strong><div><button onClick={() => featured && onAdd(featured)}>Add to order</button><button aria-label="View featured dish" onClick={() => featured && onSelect(featured)}><ArrowRight size={14} /></button></div></div></section>
    <section className="worldplate-voices"><span className="worldplate-kicker">What they say</span><h2>Guests love the journey</h2><div>{[['Every plate felt familiar and completely new at the same time.', 'Nusrat Ahmed'], ['Beautiful presentation, bold flavours, and truly warm service.', 'Rafi Hasan'], ['The signature dish is worth coming back for again and again.', 'Tania Noor']].map(([copy, name]) => <article key={name}><Quote size={18} /><span>★★★★★</span><p>{copy}</p><b>{name}</b><small>Verified guest</small></article>)}</div></section>
    <section className="worldplate-chef" id="worldplate-chef"><div><ChefHat size={82} /><span /></div><article><span className="worldplate-kicker">Meet our chef</span><h2>Cooking without borders</h2><p>Our chef blends local produce with techniques and flavours gathered from kitchens around the world.</p><b>Chef Arman Rahman</b><small>Executive chef · 14 years of experience</small></article></section>
    <footer className="worldplate-footer"><a className="worldplate-logo" href="#worldplate-home"><Flame size={17} />WorldPlate</a><p>{restaurantName} · {outlet}, Dhaka</p><button onClick={onMenu}>Order now <ArrowRight size={13} /></button></footer>
  </div>
}
