import { useState } from 'react'
import { Link,useNavigate } from 'react-router-dom'
import { ArrowRight,Utensils } from 'lucide-react'
import { useAuth } from '../contexts/AuthContext'

const Field=({label,...props})=><label className="auth-field"><span>{label}</span><input required {...props}/></label>
const SelectField=({label,children,...props})=><label className="auth-field"><span>{label}</span><select {...props}>{children}</select></label>

export function LoginPage(){const auth=useAuth(),navigate=useNavigate();const [form,setForm]=useState({email:'',password:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async(event)=>{event.preventDefault();setBusy(true);setError('');try{await auth.login(form);navigate('/admin')}catch(err){setError(err.status===401?'Email or password is incorrect.':'Login failed. Please try again.')}finally{setBusy(false)}};return <AuthShell title="Welcome back" text="Log in with the credentials you created for your restaurant."><form onSubmit={submit}><Field label="Email / username" type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/><Field label="Password" type="password" minLength="8" value={form.password} onChange={event=>setForm({...form,password:event.target.value})}/>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="saas-button" disabled={busy}>{busy?'Logging in…':'Log in'} <ArrowRight size={15}/></button></form><p>New to BiteLink? <Link to="/register">Start a free trial</Link></p></AuthShell>}

export function RegisterPage(){const auth=useAuth(),navigate=useNavigate();const [form,setForm]=useState({displayName:'',email:'',password:'',tenantName:'',tenantSlug:'',restaurantName:'',restaurantSlug:'',outletName:'',outletSlug:'',templateKey:'editorial',themeKey:'coral'}),[error,setError]=useState(''),[busy,setBusy]=useState(false);const set=key=>event=>setForm({...form,[key]:event.target.value});const submit=async(event)=>{event.preventDefault();setBusy(true);setError('');try{await auth.register(form);navigate('/admin')}catch(err){setError(err.status===409?'That email or business slug is already registered.':'Registration failed. Check the form and try again.')}finally{setBusy(false)}};return <AuthShell title="Start your 7-day free trial" text="Create your credentials, first restaurant, outlet, and customer template. No card required."><form className="register-form" onSubmit={submit}><Field label="Your name" value={form.displayName} onChange={set('displayName')}/><Field label="Work email / username" type="email" value={form.email} onChange={set('email')}/><Field label="Password" type="password" minLength="8" value={form.password} onChange={set('password')}/><Field label="Business name" value={form.tenantName} onChange={set('tenantName')}/><Field label="Business slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="my-business" value={form.tenantSlug} onChange={set('tenantSlug')}/><Field label="Restaurant name" value={form.restaurantName} onChange={set('restaurantName')}/><Field label="Restaurant slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="my-restaurant" value={form.restaurantSlug} onChange={set('restaurantSlug')}/><Field label="First outlet" value={form.outletName} onChange={set('outletName')}/><Field label="Outlet slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="dhanmondi" value={form.outletSlug} onChange={set('outletSlug')}/><SelectField label="Customer website template" value={form.templateKey} onChange={set('templateKey')}><option value="editorial">Editorial</option><option value="ember">Ember</option><option value="future-neon">Future Neon</option><option value="bistro">Bistro</option><option value="express">Express</option><option value="sage">Sage</option><option value="world-plate">World Plate</option></SelectField><SelectField label="Brand colour" value={form.themeKey} onChange={set('themeKey')}><option value="coral">Coral</option><option value="saffron">Saffron</option><option value="olive">Olive</option></SelectField>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="saas-button" disabled={busy}>{busy?'Creating trial…':'Start 7-day free trial'} <ArrowRight size={15}/></button></form><p>Already registered? <Link to="/login">Log in</Link></p></AuthShell>}

function AuthShell({title,text,children}){return <main className="auth-page"><Link className="saas-brand" to="/"><Utensils size={19}/> Bite<span>Link</span></Link><section className="auth-card"><span className="saas-kicker">BiteLink account</span><h1>{title}</h1><p>{text}</p>{children}</section></main>}
