import { ArrowLeft, Mail, Utensils } from 'lucide-react'
import { Link } from 'react-router-dom'
import SiteFooter from '../components/SiteFooter'

const content = {
  about: { eyebrow: 'About BiteLink', title: 'Better service, from scan to settlement.', intro: 'BiteLink gives restaurants a polished digital guest experience and a practical operations workspace in one connected platform.', sections: [['What we do', 'We help restaurant teams publish digital menus, accept QR orders, coordinate service, manage outlets, and understand performance without stitching together disconnected tools.'], ['Who we build for', 'BiteLink is designed for independent restaurants, growing hospitality groups, managers, kitchen teams, and service staff who need software that stays out of the way.'], ['Our approach', 'We value clear workflows, dependable access controls, mobile-first experiences, and thoughtful design for both guests and restaurant teams.']] },
  terms: { eyebrow: 'Legal', title: 'Terms & conditions', intro: 'These terms describe the rules for accessing and using the BiteLink platform. Last updated: August 29, 2026.', sections: [['Using BiteLink', 'You must provide accurate account information, protect your credentials, and use the service only for lawful restaurant operations. You are responsible for activity performed through your account.'], ['Subscriptions and trials', 'Trial and paid-plan details are presented before activation. Applicable charges, renewal dates, and cancellation terms will be shown in your account or order confirmation.'], ['Restaurant content', 'You retain responsibility for menus, prices, images, customer information, and other content you submit. You confirm that you have the rights needed to use that content.'], ['Availability and liability', 'We work to provide a reliable service, but uninterrupted availability cannot be guaranteed. To the extent permitted by law, BiteLink is not liable for indirect or consequential losses.'], ['Contact', 'Questions about these terms can be sent to support@bitelink.app.']] },
  privacy: { eyebrow: 'Legal', title: 'Privacy policy', intro: 'This policy explains how BiteLink handles information when restaurants and their teams use the platform. Last updated: August 29, 2026.', sections: [['Information we collect', 'We may process account details, restaurant information, service activity, device data, and support messages needed to operate and secure the platform.'], ['How information is used', 'Information is used to deliver the service, authenticate users, support restaurant operations, prevent abuse, improve the product, and communicate important account updates.'], ['Sharing and retention', 'We do not sell personal information. Data may be shared with service providers that help us operate BiteLink, or when required by law, and retained only as reasonably necessary.'], ['Your choices', 'You may request access, correction, or deletion of eligible personal information by contacting the platform team. Some records may be retained for legal or security reasons.'], ['Contact', 'Privacy questions and requests can be sent to support@bitelink.app.']] },
  cookies: { eyebrow: 'Legal', title: 'Cookie policy', intro: 'This policy explains how BiteLink uses browser storage and similar technologies. Last updated: August 29, 2026.', sections: [['Essential storage', 'BiteLink may use essential cookies or local browser storage to maintain sessions, remember security settings, and provide requested platform features.'], ['Analytics', 'Where enabled, limited analytics may help us understand product performance and improve usability. Optional technologies should only be used with the required consent.'], ['Managing cookies', 'You can control cookies through your browser settings. Blocking essential storage may prevent sign-in or other platform features from working correctly.']] },
}

export function InfoPage({type}) {
  const page = content[type]
  return <div className="info-site"><header className="info-header"><Link className="saas-brand" to="/"><Utensils size={19}/> Bite<span>Link</span></Link><Link to="/"><ArrowLeft size={16}/> Back to home</Link></header><main className="info-page"><span className="saas-kicker">{page.eyebrow}</span><h1>{page.title}</h1><p className="info-intro">{page.intro}</p><div className="info-sections">{page.sections.map(([title, text]) => <section key={title}><h2>{title}</h2><p>{text}</p></section>)}</div></main><SiteFooter/></div>
}

export function ContactPage() {
  return <div className="info-site"><header className="info-header"><Link className="saas-brand" to="/"><Utensils size={19}/> Bite<span>Link</span></Link><Link to="/"><ArrowLeft size={16}/> Back to home</Link></header><main className="info-page contact-page"><span className="saas-kicker">Contact</span><h1>Let’s talk about your restaurant.</h1><p className="info-intro">Our platform team can help with plans, onboarding, technical questions, or your existing account.</p><a className="contact-card" href="mailto:support@bitelink.app?subject=BiteLink%20support"><Mail size={24}/><span><small>Email the platform team</small><b>support@bitelink.app</b><em>We aim to reply within one business day.</em></span></a></main><SiteFooter/></div>
}
