import { useState } from 'react'
import { ArrowLeft,ArrowRight,Check,Plus,Trash2,Utensils } from 'lucide-react'
import { Link,useNavigate } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import { futuristicTemplateCatalog } from '../data/templateCatalog'

const stepNames=['Account','Restaurant','Template','Branding','Menu','Offers','Launch']
const slugify=value=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const newItem=()=>({name:'',slug:'',description:'',imageUrl:'',price:'',preparationMinutes:20,featured:false})
const newCategory=()=>({name:'',slug:'',description:'',items:[newItem()]})
export default function TrialSetupPage(){
 const auth=useAuth(),navigate=useNavigate(),templates=futuristicTemplateCatalog
 const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [form,setForm]=useState({displayName:'',email:'',password:'',tenantName:'',tenantSlug:'',restaurantName:'',restaurantSlug:'',outletName:'',outletSlug:'',templateKey:'future-neon',themeKey:'coral',profile:{tagline:'',description:'',coverImageUrl:'',phone:'',email:'',chefName:''},categories:[newCategory()],offers:[]})
 const set=(key,value)=>setForm(current=>({...current,[key]:value})),profile=(key,value)=>setForm(current=>({...current,profile:{...current.profile,[key]:value}}))
 const category=(index,key,value)=>setForm(current=>({...current,categories:current.categories.map((entry,i)=>i===index?{...entry,[key]:value}:entry)}))
 const item=(ci,ii,key,value)=>setForm(current=>({...current,categories:current.categories.map((entry,i)=>i===ci?{...entry,items:entry.items.map((dish,j)=>j===ii?{...dish,[key]:value}:dish)}:entry)}))
 const offer=(index,key,value)=>setForm(current=>({...current,offers:current.offers.map((entry,i)=>i===index?{...entry,[key]:value}:entry)}))
 const next=()=>{const accountOk=form.displayName&&form.email&&form.password.length>=8,restaurantOk=form.tenantName&&form.tenantSlug&&form.restaurantName&&form.restaurantSlug&&form.outletName&&form.outletSlug,brandingOk=form.profile.tagline&&form.profile.description;const ok=step===0?accountOk:step===1?restaurantOk:step===3?brandingOk:true;if(!ok){setError(step===0?'Enter your name, email, and a password of at least 8 characters.':step===1?'Complete the business, restaurant, and outlet details.':'Add a hero title and restaurant description.');return}setError('');setStep(value=>value+1)}
 const submit=async()=>{setBusy(true);setError('');try{await auth.register({...form,categories:form.categories.filter(c=>c.name).map(c=>({...c,slug:c.slug||slugify(c.name),items:c.items.filter(i=>i.name).map(i=>({...i,slug:i.slug||slugify(i.name),price:Number(i.price)||0,preparationMinutes:Number(i.preparationMinutes)||20}))})),offers:form.offers.filter(o=>o.name).map(o=>({...o,discountValue:Number(o.discountValue)||0}))});navigate('/admin')}catch(err){setError(err.status===409?'That email or business slug is already registered.':'Setup failed. Please check the fields and try again.')}finally{setBusy(false)}}
 return <main className="trial-setup"><header><Link className="saas-brand" to="/"><Utensils size={19}/> Bite<span>Link</span></Link><b>7-day free trial · no card required</b></header><div className="trial-layout"><aside><span>Guided restaurant setup</span><h1>Build your restaurant.</h1><p>Complete each step, then launch directly into your owner portal.</p><ol>{stepNames.map((name,index)=><li className={index===step?'active':index<step?'done':''} key={name}><i>{index<step?<Check size={13}/>:index+1}</i>{name}</li>)}</ol></aside><section className="trial-card"><div className="trial-progress"><i style={{width:`${(step+1)/stepNames.length*100}%`}}/></div><small className="saas-kicker">Step {step+1} of {stepNames.length}</small>
 {step===0&&<Panel title="Create your owner login" text="Use these credentials whenever you enter the admin portal."><Input label="Your name" value={form.displayName} onChange={v=>set('displayName',v)}/><Input label="Work email" type="email" value={form.email} onChange={v=>set('email',v)}/><Input label="Password" type="password" value={form.password} onChange={v=>set('password',v)}/></Panel>}
 {step===1&&<Panel title="Restaurant and outlet" text="Start with one outlet. You can add more after launch."><AutoInput label="Business name" value={form.tenantName} onChange={v=>{set('tenantName',v);set('tenantSlug',slugify(v))}}/><Input label="Business slug" value={form.tenantSlug} onChange={v=>set('tenantSlug',slugify(v))}/><AutoInput label="Restaurant name" value={form.restaurantName} onChange={v=>{set('restaurantName',v);set('restaurantSlug',slugify(v))}}/><Input label="Restaurant slug" value={form.restaurantSlug} onChange={v=>set('restaurantSlug',slugify(v))}/><AutoInput label="First outlet" value={form.outletName} onChange={v=>{set('outletName',v);set('outletSlug',slugify(v))}}/><Input label="Outlet slug" value={form.outletSlug} onChange={v=>set('outletSlug',slugify(v))}/></Panel>}
 {step===2&&<Panel title="Choose your customer template" text="Guests will see this mobile experience after scanning a table QR."><div className="trial-templates">{templates.map(t=><button className={form.templateKey===t.key?'selected':''} style={{'--tone':t.primary}} onClick={()=>set('templateKey',t.key)} key={t.key}><i/><b>{t.name}</b><small>{t.key}</small>{form.templateKey===t.key&&<Check size={14}/>}</button>)}</div><label><span>Brand colour</span><select value={form.themeKey} onChange={e=>set('themeKey',e.target.value)}><option value="coral">Chilli coral</option><option value="saffron">Saffron</option><option value="olive">Olive</option></select></label></Panel>}
 {step===3&&<Panel title="Branding and hero" text="Introduce your restaurant with a strong title, story, and cover image."><Input label="Hero title" value={form.profile.tagline} onChange={v=>profile('tagline',v)}/><Text label="Restaurant description" value={form.profile.description} onChange={v=>profile('description',v)}/><Input label="Hero image URL" type="url" value={form.profile.coverImageUrl} onChange={v=>profile('coverImageUrl',v)}/>{form.profile.coverImageUrl&&<img className="trial-hero" src={form.profile.coverImageUrl} alt="Hero preview"/>}<Input label="Phone" value={form.profile.phone} onChange={v=>profile('phone',v)}/><Input label="Public email" type="email" value={form.profile.email} onChange={v=>profile('email',v)}/><Input label="Chef name" value={form.profile.chefName} onChange={v=>profile('chefName',v)}/></Panel>}
 {step===4&&<Panel title="Create your opening menu" text="Add categories and dishes. Empty rows are safely ignored."><div className="trial-repeater">{form.categories.map((c,ci)=><article key={ci}><header><b>Category {ci+1}</b>{form.categories.length>1&&<button onClick={()=>set('categories',form.categories.filter((_,i)=>i!==ci))}><Trash2 size={14}/></button>}</header><Input label="Category name" value={c.name} onChange={v=>{category(ci,'name',v);category(ci,'slug',slugify(v))}}/><Text label="Description" value={c.description} onChange={v=>category(ci,'description',v)}/>{c.items.map((dish,ii)=><div className="trial-dish" key={ii}><header><b>Dish {ii+1}</b>{c.items.length>1&&<button onClick={()=>category(ci,'items',c.items.filter((_,i)=>i!==ii))}><Trash2 size={13}/></button>}</header><Input label="Dish name" value={dish.name} onChange={v=>{item(ci,ii,'name',v);item(ci,ii,'slug',slugify(v))}}/><Input label="Price (BDT)" type="number" value={dish.price} onChange={v=>item(ci,ii,'price',v)}/><Input label="Image URL" type="url" value={dish.imageUrl} onChange={v=>item(ci,ii,'imageUrl',v)}/><Input label="Cooking minutes" type="number" value={dish.preparationMinutes} onChange={v=>item(ci,ii,'preparationMinutes',v)}/><Text label="Dish description" value={dish.description} onChange={v=>item(ci,ii,'description',v)}/><label className="trial-check"><input type="checkbox" checked={dish.featured} onChange={e=>item(ci,ii,'featured',e.target.checked)}/> Featured dish</label></div>)}<button className="trial-add" onClick={()=>category(ci,'items',[...c.items,newItem()])}><Plus size={14}/> Add dish</button></article>)}</div><button className="trial-add dark" onClick={()=>set('categories',[...form.categories,newCategory()])}><Plus size={14}/> Add category</button></Panel>}
 {step===5&&<Panel title="Create a launch offer" text="This is optional. You can also create offers later."><div className="trial-repeater">{form.offers.map((o,index)=><article key={index}><header><b>Offer {index+1}</b><button onClick={()=>set('offers',form.offers.filter((_,i)=>i!==index))}><Trash2 size={14}/></button></header><Input label="Offer name" value={o.name} onChange={v=>offer(index,'name',v)}/><Text label="Description" value={o.description} onChange={v=>offer(index,'description',v)}/><label><span>Type</span><select value={o.offerType} onChange={e=>offer(index,'offerType',e.target.value)}><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option><option value="combo">Combo</option><option value="time_based">Time based</option><option value="day_based">Day based</option></select></label><Input label="Discount value" type="number" value={o.discountValue} onChange={v=>offer(index,'discountValue',v)}/></article>)}</div><button className="trial-add dark" onClick={()=>set('offers',[...form.offers,{name:'',description:'',offerType:'percentage',discountValue:10}])}><Plus size={14}/> Add offer</button></Panel>}
 {step===6&&<Panel title="Review and launch" text="Your restaurant, website, menu, and seven-day trial will be created together."><div className="trial-review"><article><small>Restaurant</small><b>{form.restaurantName||'Unnamed restaurant'}</b><span>{form.outletName} · {form.tenantName}</span></article><article><small>Template</small><b>{templates.find(t=>t.key===form.templateKey)?.name}</b><span>{form.profile.tagline||'Add a hero title later'}</span></article><article><small>Menu</small><b>{form.categories.filter(c=>c.name).length} categories</b><span>{form.categories.reduce((n,c)=>n+c.items.filter(i=>i.name).length,0)} dishes · {form.offers.filter(o=>o.name).length} offers</span></article><article className="highlight"><small>Subscription</small><b>7 days free</b><span>No card required.</span></article></div></Panel>}
 {error&&<p className="auth-error">{error}</p>}<footer><button className="trial-back" disabled={!step||busy} onClick={()=>setStep(step-1)}><ArrowLeft size={15}/> Back</button>{step<6?<button className="saas-button" onClick={next}>Continue <ArrowRight size={15}/></button>:<button className="saas-button" disabled={busy} onClick={submit}>{busy?'Creating…':'Launch restaurant'} <ArrowRight size={15}/></button>}</footer></section></div></main>
}

function Panel({title,text,children}){return <div className="trial-panel"><h2>{title}</h2><p>{text}</p><div className="trial-fields">{children}</div></div>}
function Input({label,value,onChange,type='text'}){return <label><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
const AutoInput=Input
function Text({label,value,onChange}){return <label className="wide"><span>{label}</span><textarea rows="3" value={value} onChange={e=>onChange(e.target.value)}/></label>}
