import { Activity, ArrowRight, Bell, ChevronDown, HelpCircle, MoreHorizontal, PanelLeft, Plus, Settings, Store, Utensils } from 'lucide-react'
import { navGroups, restaurants, roles } from '../data/mockData'

export function Button({ children, className = '', ...props }) { return <button className={`ui-button ${className}`} {...props}>{children}</button> }

export function ContextBar({ context, setContext, onRoleChange }) {
  const selectedRestaurant = restaurants.find((restaurant) => restaurant.id === context.restaurantId)
  const selectedRole = roles.find((role) => role.id === context.roleId)
  const select = (key) => (event) => setContext((current) => ({ ...current, [key]: event.target.value }))
  const selectRestaurant = (event) => setContext((current) => ({ ...current, restaurantId: event.target.value, outlet: restaurants.find((restaurant) => restaurant.id === event.target.value)?.outlets[0] }))
  return <div className="context-bar"><div className="context-intro"><Activity size={16} /><span><b>Demo mode</b><small>Visualize each BiteLink experience</small></span></div><label>Role<select value={context.roleId} onChange={onRoleChange || select('roleId')}>{roles.map((role) => <option value={role.id} key={role.id}>{role.label}</option>)}</select></label>{selectedRole?.portal !== 'customer' && selectedRole?.portal !== 'super' && <><label>Restaurant<select value={context.restaurantId} onChange={selectRestaurant}>{restaurants.map((restaurant) => <option value={restaurant.id} key={restaurant.id}>{restaurant.name}</option>)}</select></label><label>Outlet<select value={context.outlet} onChange={select('outlet')}>{selectedRestaurant?.outlets.map((outlet) => <option value={outlet} key={outlet}>{outlet}</option>)}</select></label></>}<span className="context-status">{selectedRole?.label} {selectedRole?.portal === 'super' ? '• Platform wide' : selectedRole?.portal === 'customer' ? '• Table 12' : `• ${selectedRestaurant?.name}`}</span></div>
}

export function AdminSidebar({ activePage, setActivePage, collapsed, setCollapsed, context, setContext }) {
  const role = context.roleId
  const allowed = role === 'kitchen' ? ['Overview', 'Live orders'] : role === 'order' ? ['Overview', 'Live orders', 'Tables'] : role === 'outlet' ? ['Overview', 'Live orders', 'Tables', 'Menu & offers', 'Payments'] : ['Overview', 'Live orders', 'Tables', 'Menu & offers', 'Payments', 'Team', 'Analytics', 'QR codes']
  return <aside className={`sidebar ${collapsed ? 'collapsed' : ''}`}><div className="side-top"><a className="brand" href="#overview"><span className="brand-mark"><Utensils size={17} /></span><span>Bite<span>Link</span></span></a><button className="collapse-button" onClick={() => setCollapsed(!collapsed)} aria-label="Toggle navigation"><PanelLeft size={17} /></button></div>{!collapsed && <div className="restaurant-switch"><span className="restaurant-avatar">T</span><span><b>{restaurants.find((item) => item.id === context.restaurantId)?.name}</b><small>{context.outlet} outlet</small></span><ChevronDown size={15} /></div>}<nav className="portal-nav">{navGroups.map((group) => { const links = group.links.filter(([label]) => allowed.includes(label)); return links.length ? <div className="nav-group" key={group.label}>{!collapsed && <small>{group.label}</small>}{links.map(([label, Icon]) => <button key={label} className={activePage === label ? 'active' : ''} onClick={() => setActivePage(label)} title={label}><Icon size={17} /><span>{label}</span>{label === 'Live orders' && <em>8</em>}</button>)}</div> : null })}</nav>{!collapsed && <div className="side-bottom">{allowed.includes('Team') && <button onClick={() => setActivePage('Settings')}><Settings size={17} /> Settings</button>}<button onClick={() => setActivePage('Help')}><HelpCircle size={17} /> Help center</button><div className="user-chip"><span className="user-avatar">SR</span><span><b>Samira Rahman</b><small>{roles.find((role) => role.id === context.roleId)?.label}</small></span><MoreHorizontal size={17} /></div></div>}<button className="portal-switch" onClick={() => setContext((current) => ({ ...current, roleId: current.roleId === 'customer' ? 'owner' : 'customer' }))}><Store size={17} /><span>{context.roleId === 'customer' ? 'Open admin portal' : 'Preview customer view'}</span><ArrowRight size={15} /></button></aside>
}

export function Header({ title, eyebrow, action, onAction }) { return <header className="content-header"><div><span className="page-eyebrow">{eyebrow}</span><h1>{title}</h1></div><div className="header-actions"><button className="icon-button" aria-label="Notifications"><Bell size={18} /><i /></button>{action && <Button className="primary" onClick={onAction}><Plus size={16} /> {action}</Button>}</div></header> }
export function StatCard({ label, value, meta, trend, icon: Icon, tone = 'green' }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={18} /></div><span className="stat-label">{label}</span><strong>{value}</strong><span className={trend?.startsWith('+') ? 'trend up' : 'trend'}>{trend} <small>{meta}</small></span></div> }
