import { ArrowRight, ChefHat, CheckCircle2, Clock3, Hand, ListChecks, PackageCheck, ShoppingBag, Table2 } from 'lucide-react'
import { Header, StatCard } from './PortalChrome'
import useWorkspaceData from '../hooks/useWorkspaceData'

const money=(v)=>`BDT ${Number(v||0).toLocaleString('en-BD')}`
const title=(v='')=>v.charAt(0).toUpperCase()+v.slice(1).toLowerCase().replaceAll('_',' ')
const Loading=({loading,error})=>loading?<div className="panel">Loading from database…</div>:error?<div className="panel" role="alert">{error}</div>:null

export function KitchenDashboard({context}) { const {data,loading,error}=useWorkspaceData(context); const orders=(data?.orders||[]).filter(o=>['confirmed','preparing','ready','served'].includes(o.status)); const groups=[['confirmed','New / approved','coral'],['preparing','Cooking','amber'],['ready','Ready to serve','green'],['served','Served','green']]; return <><Header eyebrow={`${context.outlet} kitchen / Database queue`} title="Kitchen view"/><div className="role-intro"><ChefHat size={18}/><span>Only approved preparation work from the selected outlet is shown.</span></div><Loading loading={loading} error={error}/><section className="stats-grid role-stats"><StatCard label="To accept" value={String(orders.filter(o=>o.status==='confirmed').length)} trend="Live" meta="approved tickets" icon={ShoppingBag} tone="coral"/><StatCard label="Cooking now" value={String(orders.filter(o=>o.status==='preparing').length)} trend="Live" meta="database queue" icon={Clock3} tone="amber"/><StatCard label="Ready to serve" value={String(orders.filter(o=>o.status==='ready').length)} trend="Live" meta="handoff queue" icon={PackageCheck}/></section><div className="kitchen-board">{groups.map(([status,label,tone])=>{const rows=orders.filter(o=>o.status===status);return <section className="kitchen-column" key={status}><div className="column-title"><span className={`status ${tone}`}>{status.toUpperCase()}</span><b>{label}</b><strong>{rows.length}</strong></div>{!rows.length&&<p>No tickets.</p>}{rows.map(o=><article className="kitchen-ticket" key={o.id}><div><b>#{o.order_number}</b><span>Table {o.table_number}</span></div><p>{o.items}</p><span>{money(o.grand_total)}</span>{o.review_rating&&<small>Customer review: {o.review_rating}/5{o.review_comment?` - ${o.review_comment}`:''}</small>}</article>)}</section>})}</div></> }

export function OrderStaffDashboard({context}) { const {data,loading,error}=useWorkspaceData(context); const orders=data?.orders||[],requests=data?.requests||[],tables=data?.tables||[]; return <><Header eyebrow={`${context.outlet} service desk`} title="Service desk"/><div className="role-intro"><ListChecks size={18}/><span>Orders, tables, and requests from PostgreSQL.</span></div><Loading loading={loading} error={error}/><section className="stats-grid role-stats"><StatCard label="New orders" value={String(orders.filter(o=>o.status==='pending').length)} trend="Live" meta="needs action" icon={ShoppingBag} tone="coral"/><StatCard label="Open tables" value={String(tables.filter(t=>t.status!=='available'&&t.status!=='disabled').length)} trend="Live" meta="on the floor" icon={Table2}/><StatCard label="Requests" value={String(requests.filter(r=>r.status==='open').length)} trend="Live" meta="from guests" icon={Hand} tone="amber"/></section><div className="panel role-list-panel"><div className="panel-heading"><div><span className="panel-kicker">Database queue</span><h2>Service actions</h2></div></div>{!orders.length&&!requests.length&&<p>No service actions waiting.</p>}{orders.slice(0,3).map(o=><div className="role-task" key={o.id}><span className="user-avatar">{o.order_number}</span><div><b>{title(o.status)} order</b><small>Table {o.table_number}</small></div><button className="text-button">Open <ArrowRight size={14}/></button></div>)}</div></> }

export function OutletDashboard({context}) { const {data,loading,error}=useWorkspaceData(context); const m=data?.metrics; return <><Header eyebrow={`${context.outlet} outlet / Operations`} title="Outlet overview"/><div className="role-intro"><CheckCircle2 size={18}/><span>This database view is scoped to the selected outlet.</span></div><Loading loading={loading} error={error}/><section className="stats-grid role-stats"><StatCard label="Today's sales" value={money(m?.revenueToday)} trend="Live" meta="completed orders" icon={ShoppingBag}/><StatCard label="Orders today" value={String(m?.ordersToday??0)} trend="Live" meta="database queue" icon={ListChecks} tone="coral"/><StatCard label="Active tables" value={`${m?.activeTables??0} / ${m?.totalTables??0}`} trend="Live" meta="right now" icon={Table2}/></section><div className="panel role-list-panel"><div className="panel-heading"><div><span className="panel-kicker">Outlet health</span><h2>Current priorities</h2></div></div>{(data?.orders?.length||data?.payments?.length||data?.requests?.length)?<><div className="role-task"><CheckCircle2 size={17}/><div><b>{data.orders.length} orders in the database</b><small>{context.outlet} outlet</small></div></div><div className="role-task"><CheckCircle2 size={17}/><div><b>{data.payments.length} payment records</b><small>{context.outlet} outlet</small></div></div></>:<p>No operational priorities yet.</p>}</div></> }
