import { ArrowRight, ChefHat, CheckCircle2, Clock3, Hand, ListChecks, PackageCheck, ShoppingBag, Table2 } from 'lucide-react'
import { Header, StatCard } from './PortalChrome'
import { orderRows } from '../data/mockData'

export function KitchenDashboard({ context }) {
  return <><Header eyebrow={`${context.outlet} kitchen / Live queue`} title="Kitchen view" /><div className="role-intro"><ChefHat size={18} /><span>Keep the line moving. Only preparation work is shown here.</span></div><section className="stats-grid role-stats"><StatCard label="To prepare" value="12" trend="3 urgent" meta="active tickets" icon={ShoppingBag} tone="coral" /><StatCard label="Preparing now" value="07" trend="18 min" meta="average time" icon={Clock3} tone="amber" /><StatCard label="Ready to serve" value="04" trend="2 waiting" meta="handoff queue" icon={PackageCheck} /></section><div className="kitchen-board">{[['NEW', 'New tickets', 'coral'], ['PREPARING', 'On the pass', 'amber'], ['READY', 'Ready to serve', 'green']].map(([status, label, tone]) => <section className="kitchen-column" key={status}><div className="column-title"><span className={`status ${tone}`}>{status}</span><b>{label}</b><strong>{status === 'NEW' ? 3 : status === 'PREPARING' ? 5 : 4}</strong></div>{orderRows.slice(0, status === 'READY' ? 2 : 3).map(([id, table, items, amount]) => <article className="kitchen-ticket" key={`${status}-${id}`}><div><b>{id}</b><span>Table {table}</span></div><p>{items}</p><span>{amount}</span><button className="ticket-action">{status === 'NEW' ? 'Start preparing' : status === 'PREPARING' ? 'Mark ready' : 'Hand to service'} <ArrowRight size={13} /></button></article>)}</section>)}</div></>
}
export function OrderStaffDashboard({ context }) {
  return <><Header eyebrow={`${context.outlet} service desk`} title="Service desk" /><div className="role-intro"><ListChecks size={18} /><span>Orders, tables, and requests in one focused workspace.</span></div><section className="stats-grid role-stats"><StatCard label="New orders" value="08" trend="3 just now" meta="needs action" icon={ShoppingBag} tone="coral" /><StatCard label="Open tables" value="09" trend="50% occupied" meta="on the floor" icon={Table2} /><StatCard label="Requests" value="03" trend="1 urgent" meta="from guests" icon={Hand} tone="amber" /></section><div className="panel role-list-panel"><div className="panel-heading"><div><span className="panel-kicker">Next actions</span><h2>Service queue</h2></div></div>{[['#1048', 'Table 06', 'New order received', 'Confirm order'], ['#1047', 'Table 03', 'Guest requested bill', 'View request'], ['#1046', 'Table 11', 'Order ready for service', 'Mark served']].map(([id, table, task, action]) => <div className="role-task" key={id}><span className="user-avatar">{id.slice(1)}</span><div><b>{task}</b><small>{id} · {table}</small></div><button className="text-button">{action} <ArrowRight size={14} /></button></div>)}</div></>
}

export function OutletDashboard({ context }) {
  return <><Header eyebrow={`${context.outlet} outlet / Operations`} title="Outlet overview" /><div className="role-intro"><CheckCircle2 size={18} /><span>This view is scoped to the selected outlet only.</span></div><section className="stats-grid role-stats"><StatCard label="Today's sales" value="BDT 24,680" trend="+12.8%" meta="vs last Monday" icon={ShoppingBag} /><StatCard label="Orders today" value="48" trend="8 new" meta="active queue" icon={ListChecks} tone="coral" /><StatCard label="Active tables" value="09 / 18" trend="50% occupied" meta="right now" icon={Table2} /></section><div className="panel role-list-panel"><div className="panel-heading"><div><span className="panel-kicker">Outlet health</span><h2>Today's priorities</h2></div></div>{['Confirm 3 new guest orders', 'Review 6 Bangla QR payments', 'Restock table cards for section B'].map((task) => <div className="role-task" key={task}><CheckCircle2 size={17} /><div><b>{task}</b><small>{context.outlet} outlet</small></div><button className="text-button">Open <ArrowRight size={14} /></button></div>)}</div></>
}
